version: "3.9" # optional since v1.27.0
services:
  crystal:
    build: .
    container_name: crystal
    environment:
      - DATABASE_URL=postgres://crystal_user:3155@crystal_db_dev/crystal_db_dev
    depends_on:
      - crystal_db_dev
    ports:
      - 45246:8080
    volumes:
      - ./src:/App/src
      - ./node_modules:/App/node_modules
      - ./prisma:/App/prisma
      - ./public:/App/public
      - ./index.ts:/App/index.ts
      - ./.cqx:/App/.cqx
      - ./.env:/App/.env
      - ./.info.env:/App/.info.env
      - ./tsconfig.json:/App/tsconfig.json

  crystal_db_dev:
    image: postgres
    container_name: crystal_db_dev
    environment:
      - POSTGRES_USER=crystal_user
      - POSTGRES_DB=crystal_db_dev
      - POSTGRES_PASSWORD=3155
    ports:
      - 50735:5432
    volumes:
      - crystal_vol_dev:/var/lib/postgresql/data

volumes:
  crystal_vol_dev:
    driver: local
