version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2

executors:
  ubuntu-default:
    machine:
      image: ubuntu-2004:current
    environment:
      VERSION: 1.3.0
      REGISTRY_URL: docker.pkg.dev
      REPO: crystal
      GOOGLE_COMPUTE_ZONE: europe-north1
      SERVICE_NAME: crystal
      IMAGE_NAME: ${GOOGLE_COMPUTE_ZONE}-docker.pkg.dev/${GOOGLE_PROJECT_ID}/${REPO}/${SERVICE_NAME}:${VERSION}

jobs:
  build_deploy_on_cloud_run:
    executor: ubuntu-default
    steps:
      - run: ""

  gcloud:
    executor: ubuntu-default
    steps:
      - run:
          name: Initialize gcloud CLI to connect to Google cloud
          shell: bash
          command: |
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
          # gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE

  nodejs_build:
    executor: ubuntu-default
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v1-{{checksum "yarn.lock"}}
      - run: yarn install
      - run: yarn install -D cqx@latest
      - save_cache:
          paths:
            - ./node_modules
          key: yarn-v1-{{checksum "yarn.lock"}}
      - run: cqx build
      - store_artifacts:
          path: ./build

workflows:
  launch:
    jobs:
      # - build_deploy_on_cloud_run
      - gcloud
      - nodejs_build
