version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - checkout
      - run: node --version
      - run: ls
      - run: pwd
      - run: cat /etc/issue
      - store_artifacts:
          path: .cqx
      - persist_to_workspace:
          root: .
          paths:
            - "."
  
  push:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t crystal -f Dockerfile.prod .
      - run: docker push dykoffi/crystal:2.0.0
    parallelism: 4

workflows:
  launch:
    jobs:
      - build
      - push:
          requires:
            - build