version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.8.0
    steps:
      - checkout
      - run: node --version
      - run: ls
      - run: pwd
      - run: cat /etc/issue
      - run: docker build -t crystal -f Dockerfile.prod .
      - store_artifacts:
          path: .cqx
    parallelism: 4
